add failing powershell replacer tests part 9

diff --git a/.github/workflows/pr-windows-script-replacer-tests.yml b/.github/workflows/pr-windows-script-replacer-tests.yml
--- a/.github/workflows/pr-windows-script-replacer-tests.yml
+++ b/.github/workflows/pr-windows-script-replacer-tests.yml
@@ -50,13 +50,26 @@ jobs:
       - name: Verify older situation
         shell: powershell
         run: |
-          Get-Command lando | Select-Object -ExpandProperty Source | Select-String -Pattern "$env:USERPROFILE\.lando\bin\lando.cmd" -SimpleMatch -ErrorAction Stop
-          lando version | Select-String -Pattern "${{ matrix.old-version }}" -SimpleMatch -ErrorAction Stop
+          $ErrorActionPreference = "Stop"
+          try {
+            Get-Command lando | Select-Object -ExpandProperty Source | Select-String -Pattern "$env:USERPROFILE\.lando\bin\lando.cmd" -SimpleMatch
+            lando version | Select-String -Pattern "${{ matrix.old-version }}" -SimpleMatch
+          } catch {
+            Write-Error "Error: Pattern not found."
+            exit 1
+          }
+
       - name: Replace Lando with setup-script
         shell: powershell
         run: .\setup-lando.ps1 -Version=${{ matrix.version }} -NoSetup
       - name: Verify new situation
         shell: powershell
         run: |
-          Get-Command lando | Select-Object -ExpandProperty Source | Select-String -Pattern "$env:USERPROFILE\.lando\bin\lando.exe" -SimpleMatch -ErrorAction Stop
-          lando version | Select-String -Pattern "${{ matrix.version }}" -SimpleMatch -ErrorAction Stop
+          $ErrorActionPreference = "Stop"
+          try {
+            Get-Command lando | Select-Object -ExpandProperty Source | Select-String -Pattern "$env:USERPROFILE\.lando\bin\lando.exe" -SimpleMatch -ErrorAction Stop
+            lando version | Select-String -Pattern "${{ matrix.version }}" -SimpleMatch -ErrorAction Stop
+          } catch {
+            Write-Error "Error: Pattern not found."
+            exit 1
+          }
